# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/person.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import base_pb2 as proto_dot_base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/person.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12proto/person.proto\x1a\x10proto/base.proto\"T\n\x04Name\x12\r\n\x05\x66irst\x18\x01 \x01(\t\x12\x0e\n\x06middle\x18\x02 \x01(\t\x12\x0c\n\x04last\x18\x03 \x01(\t\"\x1f\n\x04Type\x12\t\n\x05\x42IRTH\x10\x00\x12\x0c\n\x08MARRIAGE\x10\x01\"\xe0\x01\n\x05\x45vent\x12\x13\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x05.Date\x12\x1b\n\x08location\x18\x02 \x01(\x0b\x32\t.Location\x12\"\n\x05\x62irth\x18\x03 \x01(\x0b\x32\x11.Event.BirthEventH\x00\x12(\n\x08marriage\x18\x04 \x01(\x0b\x32\x14.Event.MarriageEventH\x00\x12\"\n\x05\x64\x65\x61th\x18\x05 \x01(\x0b\x32\x11.Event.DeathEventH\x00\x1a\x0c\n\nBirthEvent\x1a\x0f\n\rMarriageEvent\x1a\x0c\n\nDeathEventB\x06\n\x04\x64\x61ta\"B\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x14\n\x05names\x18\x02 \x03(\x0b\x32\x05.Name\x12\x16\n\x06\x65vents\x18\x03 \x03(\x0b\x32\x06.Event'
  ,
  dependencies=[proto_dot_base__pb2.DESCRIPTOR,])



_NAME_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Name.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BIRTH', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MARRIAGE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=93,
  serialized_end=124,
)
_sym_db.RegisterEnumDescriptor(_NAME_TYPE)


_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first', full_name='Name.first', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='middle', full_name='Name.middle', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last', full_name='Name.last', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NAME_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=124,
)


_EVENT_BIRTHEVENT = _descriptor.Descriptor(
  name='BirthEvent',
  full_name='Event.BirthEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=312,
)

_EVENT_MARRIAGEEVENT = _descriptor.Descriptor(
  name='MarriageEvent',
  full_name='Event.MarriageEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=329,
)

_EVENT_DEATHEVENT = _descriptor.Descriptor(
  name='DeathEvent',
  full_name='Event.DeathEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=343,
)

_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='Event.date', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='Event.location', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='birth', full_name='Event.birth', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marriage', full_name='Event.marriage', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='death', full_name='Event.death', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EVENT_BIRTHEVENT, _EVENT_MARRIAGEEVENT, _EVENT_DEATHEVENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='Event.data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=127,
  serialized_end=351,
)


_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Person.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='names', full_name='Person.names', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='events', full_name='Person.events', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=419,
)

_NAME_TYPE.containing_type = _NAME
_EVENT_BIRTHEVENT.containing_type = _EVENT
_EVENT_MARRIAGEEVENT.containing_type = _EVENT
_EVENT_DEATHEVENT.containing_type = _EVENT
_EVENT.fields_by_name['date'].message_type = proto_dot_base__pb2._DATE
_EVENT.fields_by_name['location'].message_type = proto_dot_base__pb2._LOCATION
_EVENT.fields_by_name['birth'].message_type = _EVENT_BIRTHEVENT
_EVENT.fields_by_name['marriage'].message_type = _EVENT_MARRIAGEEVENT
_EVENT.fields_by_name['death'].message_type = _EVENT_DEATHEVENT
_EVENT.oneofs_by_name['data'].fields.append(
  _EVENT.fields_by_name['birth'])
_EVENT.fields_by_name['birth'].containing_oneof = _EVENT.oneofs_by_name['data']
_EVENT.oneofs_by_name['data'].fields.append(
  _EVENT.fields_by_name['marriage'])
_EVENT.fields_by_name['marriage'].containing_oneof = _EVENT.oneofs_by_name['data']
_EVENT.oneofs_by_name['data'].fields.append(
  _EVENT.fields_by_name['death'])
_EVENT.fields_by_name['death'].containing_oneof = _EVENT.oneofs_by_name['data']
_PERSON.fields_by_name['names'].message_type = _NAME
_PERSON.fields_by_name['events'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['Name'] = _NAME
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Name = _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), {
  'DESCRIPTOR' : _NAME,
  '__module__' : 'proto.person_pb2'
  # @@protoc_insertion_point(class_scope:Name)
  })
_sym_db.RegisterMessage(Name)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {

  'BirthEvent' : _reflection.GeneratedProtocolMessageType('BirthEvent', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_BIRTHEVENT,
    '__module__' : 'proto.person_pb2'
    # @@protoc_insertion_point(class_scope:Event.BirthEvent)
    })
  ,

  'MarriageEvent' : _reflection.GeneratedProtocolMessageType('MarriageEvent', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_MARRIAGEEVENT,
    '__module__' : 'proto.person_pb2'
    # @@protoc_insertion_point(class_scope:Event.MarriageEvent)
    })
  ,

  'DeathEvent' : _reflection.GeneratedProtocolMessageType('DeathEvent', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_DEATHEVENT,
    '__module__' : 'proto.person_pb2'
    # @@protoc_insertion_point(class_scope:Event.DeathEvent)
    })
  ,
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'proto.person_pb2'
  # @@protoc_insertion_point(class_scope:Event)
  })
_sym_db.RegisterMessage(Event)
_sym_db.RegisterMessage(Event.BirthEvent)
_sym_db.RegisterMessage(Event.MarriageEvent)
_sym_db.RegisterMessage(Event.DeathEvent)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'proto.person_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  })
_sym_db.RegisterMessage(Person)


# @@protoc_insertion_point(module_scope)
